include::../attribute.adoc[]

== セッションの目的

* 今後の検討に役立つ情報の提供
** 一般的なオブザーバビリティの考え方、ユースケース
** 具体的な他社事例
** 実践的なプラクティス

== 背景

=== なぜ、オブザーバビリティが求められているのか
* ビジネスを阻害する様々な課題が発生しています。みんながそれに頭を悩ませています。
* それを解決する方法として、オブザーバビリティが世間の注目を集めています。

==== 課題
* システムの複雑化
** 複数のクラウドやSaaSを利用し、マイクロサービス化でシステムを開発しています。
** 問題の原因を特定することが難しくなり時間が掛かる。
** 膨大で多様なデータの入手。そしてその分析。
** 重大な問題の検知漏れ、擬陽性アラートに頭を悩ませています。
* ツールのサイロ
** 監視するシステムが各種存在しており、サイロ化して運用が難しくなっています。
** 運用に職人芸が必要だったり、認知負荷(学習コスト)も高い。
* 人、組織のサイロ
** 異なるロール間のコミュニケーション、オーバーヘッドにより改善やビジネス拡大に支障が出ています。

WARNING: 対処療法的な対応に限界が来ています。部分的に監視を強化したり、アラートの閾値を調整したり、データ収集をスクリプト化したり。

==== 課題の解消

* 複雑化するシステムをわかるようにする
** 情報収集を自動化し、分析済の情報を提供
** 問題の検知漏れや擬陽性アラートを減らす
* ツールの一本化
** 学習コストを低減する
** 属人性を排除する
* コミュニケーションを効率化し、ビジネスにインサイトを提供
** システムの状態を簡単にいつでも見れる
** ビジネスに役立つ情報を提供

== オブザーバビリティとは
複雑化するシステムの内部状態を理解しやすくし、それに基づいて迅速かつ適切な行動が取れるようにするための概念です。
オブザーバビリティは問題の迅速な検出と解決、システムのパフォーマンスと信頼性の向上、そして業務効率の改善に大きく寄与します。

=== 得られる価値
オブザーバビリティを正しく活用することで、以下の効果を期待できます。

==== システムの信頼性向上
サービスの信頼性を高めるために、システムの健全性を正確に監視し、必要な対応を迅速に行うことができます。

===== 問題の早期検出とトリアージ
オブザーバビリティの高いシステムは、問題が発生した際にその兆候を迅速に検出できます。これにより、ダウンタイムやパフォーマンスの低下を最小限に抑えることが可能です。

===== 原因究明の迅速化
詳細なログ、メトリクス、トレースの情報を収集することで、問題の根本原因を迅速に特定できます。これにより、問題解決までの時間が短縮されます。

==== 開発と運用の効率化
開発者や運用チームがシステムの状態を簡単に把握できるため、デバッグやテストが効率化され、新しいリリースや機能追加がスムーズに行えます。

==== パフォーマンスの最適化
リソースの使用状況やパフォーマンスのボトルネックを明確に把握することができ、効率的な最適化が可能です。

==== ユーザーエクスペリエンスの向上
サービスの稼働状況やレスポンスタイムなどを監視し、問題が発生した際に迅速に対応できることで、ユーザーに対して安定したサービスを提供し続けることができます。

==== 予測とプロアクティブなメンテナンス
過去のデータと現在の状態を分析することで、将来の問題を予測し、事前に対策を講じることができます。これにより、未然にトラブルを防ぐことができます。

=== 主要な機能

==== データ収集

===== 収集対象のリソース
クラウドインフラ、オンプレミス、コンテナ、ミドル、アプリ・API、ブラウザ、モバイといったシステムを構成するすべての要素が対象となります。エージェントがサービスプロバイダーから提供されておりそれらを導入することで、情報を一カ所に収集することができるようになります

===== 収集対象のデータタイプ
ログ、メトリクス、トレースと呼ばれる三種類のデータを収集します。これらのデータタイプを総じてテレメトリーデータあるいは、テレメトリーと呼びます。

ログ::
システムの動作やイベントについての詳細な記録です。
ログはテキスト形式で記録され、システムの各部分がどのように動作しているかを時系列で追跡できます。
特定のエラーやイベントが何時発生したのか、原因が何であるのかを詳細に追跡できます。

メトリクス::
システムのパフォーマンスや状態を示す数値データ。
CPU使用率、メモリ使用量、リクエスト数、エラーレートなど。
通常、定期的に収集され、リアルタイムでのモニタリングやアラートに用いられます。
例えば特定の時間にCPU使用率が急上昇した場合、その原因が何かを見つける手掛かりになります。

トレース::
分散システムにおけるリクエストの流れや全体の動作を追跡するためのデータ。
特にマイクロサービスアーキテクチャで重要で、リクエストがどのサービスを経由して処理されたかを可視化します。
システム内の各サービスがどのように相互作用しているかを理解し、ボトルネックやエラーの発生源を特定できます。

==== データの統合
上述の三つの要素が相互に自動的に連携し合うことで、システム全体の状態を詳細に効率的に理解できるようになります。

TIP: これまでは、以下のような複数のツールを使い分け、運用者が情報を統合し分析していました。それぞれのツールを正しく理解し統合した分析をおこなうことの難しさに世間は頭を悩ませていました。

ログ管理ツール:: Elastic Stack（ELK: Elasticsearch, Logstash, Kibana）
Fluentd

メトリクス収集と監視ツール:: Prometheus,Grafana

分散トレーシングツール:: Jaeger,Zipkin

==== データの分析・可視化
各種メトリクスやログ、トレース情報を統合的に表示する洗練されたダッシュボードが標準として提供されます。

標準のダッシュボードを利用することでシステム全体の状態がわかることは当然のことながら、簡単な操作で異常の原因を特定することができます。また、目的に合わせた専用のダッシュボードを作成することができます。

TIP: これまではそれらのビューを自分たちで作成しメンテナンスする必要がありました。作業を簡略化するためのテンプレートなども提供されていますが、そのまま使うことはできずカスタマイズして利用することが大半を占めます。


==== 異常検知とアラート
正常な動作のパターンを機械学習し、異常な動作を自動的に検出し通知します。

また、従来のように事前に設定された閾値や特定のイベントに基づいてアラートを発生。
システム管理者に異常を早期に通知し、迅速な対応を促します。

== 事例

=== 金融機関

組織観点と開発段階から価値を発揮した事例です。

SoE向けの小さな基盤と基盤を検証するためのアプリ開発。
小さな基盤が提供する標準機能としてオブザーバビリティを提供。

==== SREチームの編成

弊社要員＋顧客＋ベンダーの3社でSREチームを編成。

SREチームが主体となりオブザーバビリティツールを導入。システムを可観測にしリリース後の運用を効率化することは当然のことながら、**開発段階** からその価値を発揮。

==== 性能劣化原因の迅速な特定
開発段階で、レスポンスが10秒以上掛かる問題が発生。
リリース前のためアラート設定をしておらず、開発チームから相談を受けて気づくことになったが、問題の根本原因特定まで1時間。最初に立てた仮説が当たる結果となったが、最初の仮設立案まで5分と脅威的な数値を記録。

TIP: 開発チームでは問題の原因を特定できなかった。

パフォーマンステストのシフトレフトが実現され、後続のパフォーマンステストでは大きな問題が検出されず予定通りリリースすることができた。

=== 製造物流小売業

オブザーバビリティツールを高度に利用しセルフヒーリングを可能にする事例です。

==== プログレッシブデリバリー
CICDにおけるCDの発展的な手法です。
影響範囲をきめ細かくコントロールしながら、問題の発生を自動的に検知し、ロールバックします。

**セミナー資料を元に詳細を書く**

=== 製造業

運用体制・プロセスが確立しておらず価値を得ることができていなかった事例。

==== 運用体制・プロセスを確立することでその真価を発揮する

旧来型の運用体制・プロセスの組織にオブザーバビリティツールが導入されており、システムのリソース利用状況定期レポートがメールで送信されるようになっていた。

システム管理者は、その内容を理解できておらずリソースの最適化が行われていない状態であった。

定期的にXXシステム CPU利用率3%などのメールが来ている。
本来であれば、リソース効率を最適化するためのアプローチをとるべき。

WARNING: システム管理者はそのツールの価値や使い方を理解できておらず、情報の意味もわかっていなかった。どうやって使ったらいいんでしょうかと聞かれる状態。

== 成功のカギ

=== チーム設計
宝の持ち腐れにならないように運用体制・プロセスを整理することが成功のカギとなります。既存の運用体制・プロセスは、旧来型の監視ツールに最適化されており、オブザーバビリティツールはその真価を発揮できません。

==== SREチームの編成

このアプローチは、システムの信頼性が重要なシステムで特に効果的に作用します。

SREと呼ばれるシステムの信頼性を重要指標としたエンジニアリングチームの編成し、その責務をおいます。SREと呼ばれるエンジニアリング領域は、専門性が高いため専任のチームが必要です。

==== セルフサービス型での提供と支援チームの編成

このアプローチは、アジリティが重要なシステムで特に効果的に作用します。

オブザーバビリティツールを開発チームがセルフサービスで活用できることで、迅速な対応と運用チームの負担を軽減した運用を両立することができます。

開発・運用チームがわかれており、運用チームがその責任を担う場合は、チームをまたがるコミュニケーションが発生し、迅速な対応が難しくなり運用チームの負担も大きくなります。

このアプローチは、開発チームが自分たちで利用できるようなナレッジの提供や彼らが自分たちで利用できるようになるまでの支援体制が重要になります。

=== ツール選定
各社がツールを提供しているが、主要な機能での差異はほとんどなく、カタログスペックでの比較や簡単なPoCで差異を検出することは難しいです。
ライセンス形態とセキュリティが選定のポイントになります。

==== ライセンス形態
ツールのライセンス形態は、データ量型と人数型に大別されます。想定のデータ量と利用者数で分岐点を見極めることが重要になります。

SREのようなシステム数（データ量）と人数が直結しない運用の場合は、人数型のライセンス形態が適していることが多くなります。

小規模システムでデータ量が少ない場合は、データ量型が適している。

==== セキュリティ
セルフホストできるのか。国外にデータがあっていいのかなど。ログにはセンシティブなデータが含まれガチ。

=== 明確な目標設定
オブザーバビリティを導入する目的や目標を明確にしましょう。例えば、システムの可用性を向上させる、障害対応時間を短縮するなど、具体的なゴールを設定することが重要です。

=== 包括的な計画とロードマップ作成
導入にあたっては、ステークホルダーを含めて計画を立てましょう。初期導入・評価・スケーリングに至るまでの明確なロードマップを作成します。
