include::../attribute.adoc[]

== セッションの目的
今後の検討に役立てるため、以下の実現を実現するモダンなCICDの例を共有する

- 開発者体験の向上
- 開発生産性の向上
- 品質とアジリティの両立

== 前置き
CI/CDは、**Software Development Life Cycle（ソフトウェア開発ライフサイクル）** のプロセスを効率化し、自動化するための一連のプラクティスとツールのことを指します。CI/CDは以下の2つの主要なコンポーネントから構成されます

CI（Continuous Integration 継続的インテグレーション）::
開発者が変更を頻繁にコードベースにマージするプロセスです。
各変更は自動化されたビルドとテストの一連のステップを通じて検証されます。
これにより、コードの品質が保たれ、早期にバグを発見することができるようになります。
CD（Continuous Delivery 継続的デリバリー ）::
CIの後続ステップであり、コードがプロダクション環境に安全かつ迅速にデプロイされることを目的としています。
継続的デリバリーは、アプリケーションが自動化されたテストをすべて通過する限り、手動でリリースを実行できる準備ができていることを保証します。

WARNING: CDは（Continuous Deploy 継続的デプロイ) を意図して記載されることがありますが、本セッションでは、Continuous Deliveryを意図してお話します。

下記の向上を目指すには、CICDのみならずSDLC全体に目を向ける必要があります。
本セッションでは、CICDのみならずプロジェクト管理や開発環境などSDLC全体に目を向けてお話します。

- 開発者体験の向上
- 開発生産性の向上
- 品質とアジリティの両立

=== 開発者体験とは
ソフトウェア開発者が製品、ツール、プラットフォーム、APIなどを使用する際に感じる体験全般を指します。これには以下の要素が含まれます

効率性::
開発プロセスのスムーズさや手間の少なさ

学習曲線::
新しい技術やツールを習得する際の学習の難易度

使いやすさ::
インターフェースの直感性やドキュメントの充実度

サポート::
問題解決のためのサポート体制やコミュニティの存在

パフォーマンス::
ツールやプラットフォームの性能や安定性

TIP: メッセージ：こういったものを向上していきたい。開発が楽になるように。一緒に考えてよりよくしていきたい。

=== 開発生産性とは

**Four Keysをベースに説明**

TIP: メッセージ: 効率性を測る尺度として利用していきたい。これからおこなう検討や改善によってどれだけ効果があったが上位陣に示して予算取って活動の幅を広げていきたい


== ビジョン

=== 開発
開発視点では、 ～～～のような夢を描いている。一緒に描いて、実現に向けて、活動していきたい。

- 認知負荷が低い。
- すぐに開発を始められる。
- 他のチームを待たずに進められる。
- 技術選定に制約の範囲内で自由度がある。
- 特別な学習や準備がなくても安全。
- 車輪の再発明を減らし、ナレッジやプラクティス、アーキテクチャなどが流用できる。

=== 運用
運用視点では、 ～～～のような夢を描いている。一緒に描いて、実現に向けて、活動していきたい。

- 問い合わせなくても、簡単にすぐに問題の原因がわかる
- 緊急性の低いアラートで起こされない。


== 実現例

=== 自分たちですぐに始められる。
=== 他のチームを待たない。
=== 自分たちで簡単にすぐに問題の原因がわかる

== 以下、次回予告

=== やりたいこと
==== ツールや提供形態
SDLCの軸を空欄で。どんな風に使いたいみたいな話も聞きたい。
軸に無いものがあってもいいので、そういうの無いかも聞く

=== 不満みたいなこと

