include::../attribute.adoc[]


== アジェンダ

* ゴール設計の考え方
* ゴールディスカッション
* ロードマップ/作業主体ディスカッション

== ゴール設計の考え方

ゴール設計は、長期、中期、短期でそれぞれ設定する。
計測可能で達成判断可能でなければならない。

各ゴールは、経験主義に基づきいつでも変更可能であるが、多くの場合、上位ゴールほど変更が難しい。

各ゴールで目指せるものは１つのみとなり、下位のゴールは上位ゴールを実現するための踏み石となる。

プロダクトと内製開発の２視点でゴールを設定する。

=== プロダクト視点
各ゴールは、経験主義に基づき変更可能である。下位ゴールは変更容易性が高い。それぞれのゴールは達成判断できる必要があります。

==== プロダクトビジョン（長期）
数年単位の最も長期的な視点を持ち複数のプロダクトゴールを達成することで実現される。

> 野球人の「効率的な成長」を実現​するために、これまで専門家しか出来なった上手くなるための科学的アプローチ領域をミズノが「民主化」する

==== プロダクトゴール（中期）
数ヵ月単位の視点で、複数のスプリントゴールを達成することで実現される。プロダクトビジョンへの進捗を示せる必要があります。

> １１月にフィードバックシートアプリのＭＶＰを限定公開し、市場テストを開始

> １２月に市場テスト中に得たフィードバックを収集を完了※市場テストと改善活動は継続。

> ２０２５年７月に機能拡充・改善したフィードバックシートアプリをリリースする

TIP: プロダクトゴールを達成するためにやるべきことの一覧をプロダクトバックログと呼びます。

==== スプリントゴール（短期）
スプリント毎に設定される。開発チームはスプリントゴールを実現するために日々の開発をおこなう。

TIP: スプリントゴールを達成するためにやるべきことの一覧をスプリントバックログと呼びます。

TIP: スクラムチームは、プロダクトゴールを達成するための
専門家集団です。スクラムチームはプロダクトゴールを達成するためにスプリントでスプリントゴールを目指して開発します。

=== 内製開発視点

==== ビジョン（長期）
数年単位の最も長期的な視点で設定する。
不確実で不確かな内容でよく、「～世界を夢見ている。」などで表現します。

> ミズノが自分たちでシステムを開発し、機械的に収集したデータをもとに顧客視点で改善しながら、システムを運用している世界を夢見ている。

==== 中間ゴール（中期）
数ヵ月単位の視点で設定し、積み重ねることでビジョンに近づきます。

以下、中間ゴールの例

===== システム観点

> Webアプリケーションを開発開始できる状態になる

> Webアプリケーションを信頼性高くデプロイができる状態になる。

> リソース効率、可搬性の高いWebアプリケーション実行環境を自分たちで運用できる状態になる

> Webアプリケーション上でのユーザ行動が観測可能な状態になる

> ★高コスト★ Webアプリケーションが可観測な状態になる

> ★高難易度★ 顧客認証がMIZUNO IDと統合された状態になる

> ★高難易度★ 様々なIoTデータを収集し利活用できる状態になる

> ★高難易度★ データ分析を安全に信頼性高くできる状態になる

===== スキル観点

> 開発環境とリリースの仕組みを自分たちで利用できる状態になる。

> リソース効率、可搬性の高いWebアプリケーション実行環境を簡単に利用できる状態になる。

> Webアプリケーションを指導なく自分たちで開発できるようになる

> Four Keys(デプロイ頻度、変更のリードタイム、変更障害率、サービス復元時間)のハイパフォーマンスチームになる。

> ★中難易度★ 開発環境とリリースの仕組みを自分たちで運用できる状態になる。

> ★高難易度★ リソース効率、可搬性の高いWebアプリケーション実行環境を自分たちで運用できる状態になる

> ★高難易度★ ハイブリッドアプリを指導なく自分たちで開発できるようになる。

==== スプリントゴール（短期）
スプリント毎に設定される。開発チームはスプリントゴールを実現するために日々の開発をおこ
