@startuml test

start

fork
:ユーザーストーリーマップ\nワイヤーフレーム作成;
:プロダクトバックログ作成;

end fork

:サービス設計;
:API インターフェイス設計;

fork

:バックエンド\nサービス実装・テスト;
:バックエンド\n開発環境デプロイ;

fork again

:フロントエンド\n機能実装・テスト;
:フロントエンド\n開発環境デプロイ;

end fork

:結合試験;

:スプリントレビュー;

:本番環境リリース;

end

@enduml
